version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    docker:
      - image: jhipster/jhipster:v7.7.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      # Download and cache dependencies
      - run:
          name: Print Java Version
          command: 'java -version'
      - run:
          name: Print Node Version
          command: 'node -v'
      - run:
          name: Print NPM Version
          command: 'npm -v'
      - run:
          name: Install Node Modules
          command: 'npm install'
      - save_cache:
          paths:
            - node
            - node_modules
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}-{{ checksum "package-lock.json" }}

      - run:
          name: Give Executable Power
          command: 'chmod +x mvnw'
      - run:
          name: Deploy to Heroku
          command: './mvnw -ntp com.heroku.sdk:heroku-maven-plugin:2.0.5:deploy -DskipTests -Pprod, -Dheroku.buildpacks=heroku/jvm -Dheroku.appName=app-chuck'
